# docker-compose.yml
version: "3.9"

services:
  frontend:
    build: ./frontend/
    ports:
      - "5173:5173"
  app:
    build: ./api/
    ports:
      - "3000:3000"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: elypay_local
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: